default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: maze_development

test:
  <<: *default
  database: maze_test

production:
  <<: *default
  database: maze_production
