default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: maze_development

test:
  <<: *default
  database: maze_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: maze_f4yx
  username: maze_f4yx_user
  password: JC0wFEJ7ssQRhVQpJFyxLSPQC4AM7ln4
  host: dpg-cv6jukvnoe9s73bvstfg-a
  port: 5432

