default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: ujjawalkr
  password: 12345678
  pool: 5

development:
  <<: *default
  database: maze_development

test:
  <<: *default
  database: maze_test

production:
  <<: *default
  database: maze_production
